export default defineAppConfig({
  siteName: 'Snappo',
  siteBaseUrl: 'https://snappo.me',
  defaultOgComponent: 'Pergel',

  tools: [
    {
      slug: 'jwt-decoder',
      title: 'JWT Decoder',
      badge: 'Security',
      description:
        'Decode JSON Web Token headers and payloads, inspect expiration, and verify HS256, RS256, or ES256 signatures.',
      component: 'jwtDecoderTool.vue',
      tags: ['jwt', 'json web token', 'decode', 'signature', 'security', 'authentication'],
      status: 'beta',
      accent: 'rgba(239,68,68,0.35)',
    },
    {
      slug: 'favicon-generator',
      title: 'Favicon Generator',
      badge: 'Design',
      description:
        'Create favicon, Apple, Android, and PWA icon files from an image, with ready-to-paste HTML and manifest snippets.',
      component: 'faviconGeneratorTool.vue',
      tags: ['favicon', 'icon', 'pwa', 'manifest', 'generator'],
      status: 'beta',
      accent: 'rgba(20,184,166,0.35)',
    },
    {
      slug: 'bcrypt-generator',
      title: 'Bcrypt Generator',
      subtitle:
        'Create a bcrypt hash or verify a password against an existing hash. Adjust the cost factor to compare hashing work.',
      badge: 'Hashing',
      description:
        'Create bcrypt hashes, adjust the cost factor, and verify passwords against existing hashes.',
      component: 'bcryptTool.vue',
      tags: ['security', 'hash', 'bcrypt'],
      status: 'beta',
      accent: 'rgba(16, 185, 129, 0.25)',
    },

    {
      slug: 'case-converter',
      title: 'Case Converter',
      badge: 'Text',
      description:
        'Convert text between camelCase, snake_case, PascalCase, kebab-case, and other common naming styles.',
      component: 'caseConverterTool.vue',
      tags: ['text', 'converter', 'case'],
      status: 'beta',
      accent: 'rgba(139,92,246,0.35)',
    },

    {
      slug: 'color-picker',
      title: 'Color Picker',
      badge: 'Design',
      description:
        'Pick colors and convert between HEX, RGB, and HSL values. Copy color values for use in a project.',
      component: 'colorPickerTool.vue',
      tags: ['color', 'picker', 'design'],
      status: 'beta',
      accent: 'rgba(99,102,241,0.35)',
    },
    {
      slug: 'lorem-ipsum-generator',
      title: 'Lorem Ipsum Generator',
      badge: 'Text',
      description:
        'Generate placeholder text by word, sentence, or paragraph count, with optional HTML tags.',
      component: 'loremIpsumTool.vue',
      tags: ['text', 'lorem', 'ipsum', 'generator'],
      status: 'beta',
      accent: 'rgba(244,114,182,0.35)',
    },
    {
      slug: 'regex-tester',
      title: 'Regex Tester',
      badge: 'Code',
      description:
        'Test regular expressions against sample text with highlighted matches, capture groups, and a syntax reference.',
      component: 'regexTesterTool.vue',
      tags: ['regex', 'regexp', 'test', 'debug'],
      status: 'beta',
      accent: 'rgba(34,197,94,0.35)',
    },

    {
      slug: 'diff-checker',
      title: 'Diff Checker',
      badge: 'Code',
      description:
        'Compare two text inputs side by side and inspect the lines that were added, removed, or changed.',
      component: 'diffCheckerTool.vue',
      tags: ['diff', 'compare', 'text', 'code'],
      status: 'beta',
      accent: 'rgba(59,130,246,0.35)',
    },

    {
      slug: 'palette-generator',
      title: 'Palette Generator',
      badge: 'Design',
      description:
        'Build a color palette from a base color and explore related hues, shades, and tints.',
      component: 'paletteGeneratorTool.vue',
      tags: ['palette', 'colors', 'design', 'generator'],
      status: 'beta',
      accent: 'rgba(236,72,153,0.35)',
    },

    {
      slug: 'minifier',
      title: 'Minifier',
      badge: 'Code',
      description:
        'Minify JavaScript, CSS, or HTML by removing whitespace and other unnecessary characters.',
      component: 'minifierTool.vue',
      tags: ['minify', 'javascript', 'css', 'html', 'optimize'],
      status: 'beta',
      accent: 'rgba(250,204,21,0.35)',
    },
    {
      slug: 'password-generator',
      title: 'Password Generator',
      badge: 'Security',
      description:
        'Generate passwords with a chosen length and character sets, including letters, numbers, and symbols.',
      component: 'passwordGeneratorTool.vue',
      tags: ['password', 'security', 'generator', 'random'],
      status: 'stable',
      accent: 'rgba(239,68,68,0.35)',
    },
    {
      slug: 'cron-tool',
      title: 'Cron Tool',
      badge: 'Code',
      description:
        'Build or parse cron expressions, review a readable schedule, and preview upcoming run times.',
      component: 'cronTool.vue',
      tags: ['cron', 'scheduler', 'time', 'generator', 'parser'],
      status: 'beta',
      accent: 'rgba(168,85,247,0.35)',
    },
    {
      slug: 'uuid-tool',
      title: 'UUID Tool',
      badge: 'Code',
      description:
        'Generate UUIDs in supported versions, individually or in batches, for use as unique identifiers.',
      component: 'uuidTool.vue',
      tags: ['uuid', 'generator', 'id', 'random'],
      status: 'stable',
      accent: 'rgba(14,165,233,0.35)',
    },
    {
      slug: 'border-radius-generator',
      title: 'Border Radius Generator',
      badge: 'Design',
      description:
        'Adjust corner radii in a visual preview and copy the resulting CSS border-radius value.',
      component: 'borderRadiusTool.vue',
      tags: ['border', 'radius', 'css', 'design', 'generator'],
      status: 'beta',
      accent: 'rgba(34,211,238,0.35)',
    },
    {
      slug: 'json-tool',
      title: 'JSON Tool',
      badge: 'Code',
      description:
        'Format, validate, or minify JSON. Inspect syntax errors and copy the corrected output.',
      component: 'jsonTool.vue',
      tags: ['json', 'formatter', 'validator', 'minify'],
      status: 'beta',
      accent: 'rgba(251,146,60,0.35)',
    },
    {
      slug: 'color-contrast-checker',
      title: 'Color Contrast Checker',
      badge: 'Design',
      description:
        'Check the contrast ratio between foreground and background colors against WCAG AA and AAA criteria.',
      component: 'colorContrastCheckerTool.vue',
      tags: ['color', 'contrast', 'accessibility', 'design'],
      status: 'stable',
      accent: 'rgba(132,204,22,0.35)',
    },
    {
      slug: 'box-shadow-generator',
      title: 'Box Shadow Generator',
      badge: 'Design',
      description:
        'Adjust blur, spread, offset, and color in a preview, then copy the CSS box-shadow value.',
      component: 'boxShadowGeneratorTool.vue',
      tags: ['box-shadow', 'css', 'design', 'generator'],
      status: 'beta',
      accent: 'rgba(250,204,21,0.35)',
    },
    {
      slug: 'url-encoder',
      title: 'URL Encoder / Decoder',
      badge: 'Text',
      description:
        'Encode URL values or full URLs, and decode percent-encoded text with input validation.',
      component: 'urlEncoderTool.vue',
      tags: ['url', 'uri', 'encode', 'decode', 'percent encoding'],
      status: 'stable',
      accent: 'rgba(20,184,166,0.35)',
    },
    {
      slug: 'timestamp-converter',
      title: 'Timestamp Converter',
      badge: 'Code',
      description:
        'Convert Unix timestamps to UTC dates and ISO 8601 dates to seconds or milliseconds.',
      component: 'timestampConverterTool.vue',
      tags: ['timestamp', 'unix', 'epoch', 'date', 'time', 'converter'],
      status: 'stable',
      accent: 'rgba(59,130,246,0.35)',
    },
    {
      slug: 'base64-tool',
      title: 'Base64 Encoder / Decoder',
      badge: 'Code',
      description: 'Encode UTF-8 text as Base64 or decode Base64 back to readable text.',
      component: 'base64Tool.vue',
      tags: ['base64', 'encode', 'decode', 'text', 'utf-8'],
      status: 'stable',
      accent: 'rgba(14,165,233,0.35)',
    },
    {
      slug: 'html-entities',
      title: 'HTML Entity Encoder / Decoder',
      badge: 'Code',
      description: 'Escape HTML-sensitive characters or decode common named and numeric entities.',
      component: 'htmlEntitiesTool.vue',
      tags: ['html', 'entity', 'entities', 'escape', 'decode'],
      status: 'stable',
      accent: 'rgba(249,115,22,0.35)',
    },
    {
      slug: 'number-base-converter',
      title: 'Number Base Converter',
      badge: 'Code',
      description: 'Convert whole numbers between binary, octal, decimal, and hexadecimal.',
      component: 'numberBaseConverterTool.vue',
      tags: ['number', 'base', 'binary', 'octal', 'decimal', 'hexadecimal', 'hex'],
      status: 'stable',
      accent: 'rgba(139,92,246,0.35)',
    },
    {
      slug: 'csv-to-json',
      title: 'CSV to JSON Converter',
      badge: 'Code',
      description: 'Convert CSV rows into JSON objects using the first row as column names.',
      component: 'csvToJsonTool.vue',
      tags: ['csv', 'json', 'converter', 'data'],
      status: 'stable',
      accent: 'rgba(34,197,94,0.35)',
    },
    {
      slug: 'markdown-table-generator',
      title: 'Markdown Table Generator',
      badge: 'Text',
      description: 'Turn tab-separated rows into a Markdown table with escaped cell values.',
      component: 'markdownTableTool.vue',
      tags: ['markdown', 'table', 'generator', 'gfm', 'text'],
      status: 'stable',
      accent: 'rgba(20,184,166,0.35)',
    },
    {
      slug: 'hmac-generator',
      title: 'HMAC Generator',
      badge: 'Security',
      description:
        'Generate or verify HMAC values with SHA-1, SHA-256, SHA-512, or MD5 in hex or Base64.',
      component: 'hmacTool.vue',
      tags: ['hmac', 'hash', 'authentication', 'verify', 'sha-1', 'sha-256', 'sha-512', 'md5'],
      status: 'stable',
      accent: 'rgba(239,68,68,0.35)',
    },
  ],
})
